#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    site_name: '<img src="https://www.robertwent.com/wp-content/uploads/2017/07/symfony_logo.png" width="100px"/>'
    entities:
       - App\Entity\User
       - App\Entity\Ciudad
       - App\Entity\Categoria
       - App\Entity\Servicio;
       - App\Entity\Contacto;
       - App\Entity\Mensajes;
    design:
        menu:
            - { entity: 'User', label: 'Usuarios', icon: 'user' }
            - { entity: 'Ciudad', label: 'Ciudades', icon: 'tag' }
            - { entity: 'Categoria', label: 'Categorias', icon: 'tag' }
            - { entity: 'Servicio', label: 'Categorias', icon: 'tag' }
            - { entity: 'Contacto', label: 'Categorias', icon: 'tag' }
            - { entity: 'Mensajes', label: 'Categorias', icon: 'tag' }